HCMPRE-650, HCMPRE-651,HCMPRE-731 :: Team Performance Charts
egovernments/configs pull request #3328
Opened 2024-10-09 07:27 UTC by Ramkrishna-egov

2024-10-09 08:48 UTC, holashchand requested changes

2024-10-09 08:48 UTC, holashchand commented on egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
> +    "drillChart": "averageNumberOfHousesSprayedByVillage",
Please change drillChart here to none

2024-10-09 08:48 UTC, holashchand commented on egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
> +    "drillChart": "averageNumberOfHousesSprayedByAP",
Here it should be locality one

2024-10-09 08:48 UTC, holashchand commented on egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
> +        "key": "district"
here it should be administrativeProvince

2024-10-09 08:48 UTC, holashchand commented on egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
> +        "aggrQuery": "{\"size\":0,\"aggs\":{\"AGGS\":{\"filter\":{\"bool\":{\"must\":[{\"term\":{\"Data.role.keyword\":\"DISTRIBUTOR\"}},{\"exists\":{\"field\":\"Data.boundaryHierarchy.administrative
where this query is used?

2024-10-09 08:48 UTC, holashchand commented on egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
> +      "Total_Spray_Operators"
No query has this path - for all charts

2024-10-09 08:48 UTC, holashchand commented on egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
> +        "key": "district"
it should be locality here

2024-10-09 08:48 UTC, holashchand commented on egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
> +        "key": "district"
it should be village here

2024-10-10 05:18 UTC, Ramkrishna-egov commented
Closing this PR and raising another due to conflicts

2024-10-10 05:18 UTC, closed without merging